server {
    listen       80;
    server_name  localhost;

    # 정적 파일 루트 경로
    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # 에러 페이지 설정
    error_page 404 /index.html;
}